export enum StorefrontPage {
  ADDTOCART = 'Add To Cart Page',
  BILLINGADDRESS = 'Billing Address Page',
  CART = 'Cart Page',
  CATALOG = 'Catalog Page',
  CHECKOUTADDRESS = 'Checkout Address Page',
  CHECKOUTCONFIRMATION = 'Checkout Confirmation Page',
  CHECKOUTPAYMENT = 'Checkout Payment Page',
  CHECKOUTREVIEW = 'Checkout Review Page',
  CHECKOUTSHIPPING = 'Checkout Shipping Page',
  CREATEEDITACCOUNT = 'Account Form Page',
  CUSTOMIZETEMPLATE = 'Customize Page',
  MYACCOUNT = 'My Account Page',
  VIEWORDERS = 'View Orders Page',
}
